/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gscinema;

import java.awt.HeadlessException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author e-hen
 */
public class Login extends javax.swing.JFrame {
    private Database db;

    public Login() {
        try{
            db = new Database();
            db.connect();
        } catch (SQLException e) {}
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StaffRegisteration = new javax.swing.JTabbedPane();
        Customer = new javax.swing.JPanel();
        customerloginbutton = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ic_num = new javax.swing.JTextPane();
        CustomerLoginTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        customerregisterbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cuscpassword = new javax.swing.JPasswordField();
        cuspassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cusemail = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        cusmobile = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cusic = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        cusname = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        CustomerRegistrationTitle = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        stafflogin = new javax.swing.JButton();
        staffpassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        staffid = new javax.swing.JTextPane();
        StaffLoginTitle = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        staffregister = new javax.swing.JButton();
        staffnamelabel4 = new javax.swing.JLabel();
        staffcpassword = new javax.swing.JPasswordField();
        staffpassword1 = new javax.swing.JPasswordField();
        staffnamelabel3 = new javax.swing.JLabel();
        staffnamelabel2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        staffemail = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        staffid1 = new javax.swing.JTextPane();
        staffnamelabel1 = new javax.swing.JLabel();
        staffnamelabel = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        staffname = new javax.swing.JTextPane();
        CustomerRegistrationTitle1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 450));
        setResizable(false);

        Customer.setMaximumSize(new java.awt.Dimension(480, 341));
        Customer.setMinimumSize(new java.awt.Dimension(480, 341));
        Customer.setName(""); // NOI18N

        customerloginbutton.setText("Login");
        customerloginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerloginbuttonActionPerformed(evt);
            }
        });

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Password:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("IC Number: ");
        jLabel3.setToolTipText("");

        jScrollPane1.setViewportView(ic_num);

        CustomerLoginTitle.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        CustomerLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CustomerLoginTitle.setText("CUSTOMER LOGIN");

        javax.swing.GroupLayout CustomerLayout = new javax.swing.GroupLayout(Customer);
        Customer.setLayout(CustomerLayout);
        CustomerLayout.setHorizontalGroup(
            CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerLayout.createSequentialGroup()
                        .addGroup(CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(password)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(customerloginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(CustomerLoginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CustomerLayout.setVerticalGroup(
            CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerLayout.createSequentialGroup()
                .addComponent(CustomerLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(customerloginbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StaffRegisteration.addTab("  Customer  ", Customer);

        customerregisterbutton.setText("Register");
        customerregisterbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerregisterbuttonActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Comfirm Password:");

        cuscpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuscpasswordActionPerformed(evt);
            }
        });

        cuspassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuspasswordActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Password:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Email:");
        jLabel6.setToolTipText("");

        jScrollPane3.setViewportView(cusemail);

        jScrollPane2.setViewportView(cusmobile);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Mobile Number:");
        jLabel7.setToolTipText("");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("IC Number:");
        jLabel8.setToolTipText("");

        jScrollPane4.setViewportView(cusic);

        jScrollPane5.setViewportView(cusname);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Name:");
        jLabel9.setToolTipText("");

        CustomerRegistrationTitle.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        CustomerRegistrationTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CustomerRegistrationTitle.setText("CUSTOMER REGISTRATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addComponent(cuspassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cuscpassword)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addGap(54, 54, 54))
            .addComponent(CustomerRegistrationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(customerregisterbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(CustomerRegistrationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuspassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuscpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(customerregisterbutton)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        StaffRegisteration.addTab("Customer Registeration", jPanel2);

        stafflogin.setText("Login");
        stafflogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffloginActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Password:");
        jLabel10.setToolTipText("");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Staff ID:");
        jLabel11.setToolTipText("");

        jScrollPane6.setViewportView(staffid);

        StaffLoginTitle.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        StaffLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StaffLoginTitle.setText("STAFF LOGIN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(staffpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
            .addComponent(StaffLoginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stafflogin, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(StaffLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(stafflogin)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        StaffRegisteration.addTab("        Staff        ", jPanel4);

        staffregister.setText("Register");
        staffregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffregisterActionPerformed(evt);
            }
        });

        staffnamelabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        staffnamelabel4.setText("Comfirm Password:");
        staffnamelabel4.setToolTipText("");

        staffcpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffcpasswordActionPerformed(evt);
            }
        });

        staffpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffpassword1ActionPerformed(evt);
            }
        });

        staffnamelabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        staffnamelabel3.setText("Password:");
        staffnamelabel3.setToolTipText("");

        staffnamelabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        staffnamelabel2.setText("Email:");
        staffnamelabel2.setToolTipText("");
        staffnamelabel2.setMaximumSize(null);

        jScrollPane7.setViewportView(staffemail);

        jScrollPane8.setViewportView(staffid1);

        staffnamelabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        staffnamelabel1.setText("Staff ID:");
        staffnamelabel1.setToolTipText("");

        staffnamelabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        staffnamelabel.setText("Name:");
        staffnamelabel.setToolTipText("");

        jScrollPane9.setViewportView(staffname);

        CustomerRegistrationTitle1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        CustomerRegistrationTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CustomerRegistrationTitle1.setText("Staff Registration");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CustomerRegistrationTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(staffnamelabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(staffnamelabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(staffnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane8)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(staffnamelabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(staffnamelabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(staffpassword1)
                                    .addComponent(staffcpassword)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(staffregister)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(CustomerRegistrationTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staffnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staffnamelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staffnamelabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffnamelabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffnamelabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffcpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(staffregister)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        StaffRegisteration.addTab("    Staff Registeration   ", jPanel5);

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("GSCinema");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StaffRegisteration, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StaffRegisteration))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customerloginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerloginbuttonActionPerformed
        try{
            
            String ic = ic_num.getText();
            String pass = password.getText();
            
            //check if textfield is blank
            if(pass.equals("")||ic.equals("")){
                JOptionPane.showMessageDialog(this, "Please fill in the blank");
                return;
            }
            
            ResultSet result = db.getConnection().prepareStatement(String.format("SELECT * FROM CUSTOMER WHERE IC = '%s' AND CUS_PASSWORD = '%s'",
                ic, pass)).executeQuery();
            
            if(result.next()){
                //JOptionPane.showMessageDialog(this, "Login Successful");
                //login set user personality
                Customer cus = new Customer(result.getString("ic"),result.getString("cus_name"),result.getString("email"),result.getString("cus_password"),result.getString("mobile_num"));
                /*
                //create client class
                Client c = new Client(u,db);
                
                */
                CustomerMenu menu = new CustomerMenu(cus,db);
                menu.setVisible(true);
                dispose();
            }else{
                //database not found
                JOptionPane.showMessageDialog(this, "Wrong ic or password");
                ic_num.setText("");
                password.setText("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_customerloginbuttonActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void customerregisterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerregisterbuttonActionPerformed
        
        try{
            //get information from the fills
            String name = cusname.getText();
            String ic = cusic.getText().strip();
            String phone = cusmobile.getText();
            String email = cusemail.getText();
            String pass = cuspassword.getText();
            String cpass = cuscpassword.getText();
            
            //check if information is blank
            if(name.equals("")||ic.equals("")||phone.equals("")||email.equals("")||pass.equals("")||cpass.equals("")){
                JOptionPane.showMessageDialog(this, "Please fill the blank");
                return;
            }
            
            //check if the account exists
            ResultSet rs = db.getConnection().prepareStatement(String.format("SELECT * FROM customer WHERE ic ='%s'",
                ic)).executeQuery();
            
            if(rs.next()){
                //ic is registered
                JOptionPane.showMessageDialog(this, "This account already exists");
            }
            else if (!pass.equals(cpass)){
                //check password matching{
                JOptionPane.showMessageDialog(this, "Password does not match");
                cuspassword.setText("");
                cuscpassword.setText("");                        
            }
            else{
                //create new user
                db.getConnection().prepareStatement(String.format("INSERT INTO customer VALUES ('%s','%s','%s','%s','%s')",
                        ic,name,email,pass,phone)).executeUpdate();
                //login 
                ResultSet result = db.getConnection().prepareStatement(String.format("SELECT * FROM customer WHERE ic ='%s'",
                    ic)).executeQuery();
                
                if(result.next()){
                    JOptionPane.showMessageDialog(this, "Registered Successfully");
                    Customer cus = new Customer(result.getString("ic"),result.getString("cus_name"),result.getString("email"),result.getString("cus_password"),result.getString("mobile_num"));
                    CustomerMenu menu = new CustomerMenu(cus, db);
                    menu.setVisible(true);
                    dispose();
                }
                else{
                    System.out.println("Error");
                }
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_customerregisterbuttonActionPerformed

    private void cuscpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuscpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuscpasswordActionPerformed

    private void cuspasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuspasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuspasswordActionPerformed

    private void staffloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffloginActionPerformed
        
        try{
            String id = staffid.getText();
            String pass = staffpassword.getText();
            
            //check if textfield is blank
            if(pass.equals("")||id.equals("")){
                JOptionPane.showMessageDialog(this, "Please fill in the blank");
                return;
            }
            
            ResultSet result = db.getConnection().prepareStatement(String.format("SELECT * FROM staff WHERE staffid = '%s' AND staffpassword = '%s'",
                id, pass)).executeQuery();
            
            if(result.next()){
                //JOptionPane.showMessageDialog(this, "Login Successful");
                //login set user personality
                //Customer cus = new Customer(result.getString("ic"),result.getString("name"));
                /*
                //create client class
                Client c = new Client(u,db);
                //make client layout visible
                c.setVisible(true);
                setVisible(false);
                dispose();
                */
                StaffMenu menu = new StaffMenu();
                menu.setVisible(true);
                dispose();
            }else{
                //database not found
                JOptionPane.showMessageDialog(this, "Wrong id or password");
                staffid.setText("");
                staffpassword.setText("");
            }

        }catch(HeadlessException | SQLException e){
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_staffloginActionPerformed

    private void staffregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffregisterActionPerformed
        try{
            //get information from the fills
            String name = staffname.getText();
            String id = staffid1.getText();
            String email = staffemail.getText();
            String pass = staffpassword1.getText();
            String cpass = staffcpassword.getText();
            
            //check if information is blank
            if(name.equals("")||id.equals("")||email.equals("")||pass.equals("")||cpass.equals("")){
                JOptionPane.showMessageDialog(this, "Please fill in the blank");
                return;
            }
            
            //check if the account exists
            ResultSet rs = db.getConnection().prepareStatement(String.format("SELECT * FROM staff WHERE staffid ='%s'",
                id)).executeQuery();
            
            if(rs.next()){
                //id is registered
                JOptionPane.showMessageDialog(this, "This account already exists");
            }
            else if (!pass.equals(cpass)){
                //check password matching{
                JOptionPane.showMessageDialog(this, "Password does not match");
                staffpassword1.setText("");
                staffcpassword.setText("");                        
            }
            else{
                //create new staff account
                db.getConnection().prepareStatement(String.format("INSERT INTO staff VALUES ('%s','%s','%s','%s')",
                        id,name,email,pass)).executeUpdate();
                
                //login 
                ResultSet result = db.getConnection().prepareStatement(String.format("SELECT * FROM staff WHERE staffid ='%s'",
                    id)).executeQuery();
                
                if(result.next()){
                    JOptionPane.showMessageDialog(this, "Registered Successfully");
                    //set user personality
                    //User u = new User(result.getString("name"),result.getString("ic"),result.getInt("pk"));
                    //create client class and pass parameter database and user
                    //Client c = new Client(u,db);
                    //set client jframe visible
                    //c.setVisible(true);
                    //destroy login jframe
                    //setVisible(false);
                    //dispose();
                    StaffMenu sm = new StaffMenu();
                    sm.setVisible(true);
                }
                else{
                    System.out.println("Error");
                }
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_staffregisterActionPerformed

    private void staffcpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffcpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffcpasswordActionPerformed

    private void staffpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffpassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffpassword1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Customer;
    private javax.swing.JLabel CustomerLoginTitle;
    private javax.swing.JLabel CustomerRegistrationTitle;
    private javax.swing.JLabel CustomerRegistrationTitle1;
    private javax.swing.JLabel StaffLoginTitle;
    private javax.swing.JTabbedPane StaffRegisteration;
    private javax.swing.JPasswordField cuscpassword;
    private javax.swing.JTextPane cusemail;
    private javax.swing.JTextPane cusic;
    private javax.swing.JTextPane cusmobile;
    private javax.swing.JTextPane cusname;
    private javax.swing.JPasswordField cuspassword;
    private javax.swing.JButton customerloginbutton;
    private javax.swing.JButton customerregisterbutton;
    private javax.swing.JTextPane ic_num;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField staffcpassword;
    private javax.swing.JTextPane staffemail;
    private javax.swing.JTextPane staffid;
    private javax.swing.JTextPane staffid1;
    private javax.swing.JButton stafflogin;
    private javax.swing.JTextPane staffname;
    private javax.swing.JLabel staffnamelabel;
    private javax.swing.JLabel staffnamelabel1;
    private javax.swing.JLabel staffnamelabel2;
    private javax.swing.JLabel staffnamelabel3;
    private javax.swing.JLabel staffnamelabel4;
    private javax.swing.JPasswordField staffpassword;
    private javax.swing.JPasswordField staffpassword1;
    private javax.swing.JButton staffregister;
    // End of variables declaration//GEN-END:variables
}
